version: '3.4'

services:
  ppsr-batch-registration-frontend:
    image: ppsr-batch-registration-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000