version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_strong_Passw0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: ppsr-webapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PpsrDb;User Id=sa;Password=Your_strong_Passw0rd!;TrustServerCertificate=true;
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  sqlserver_data: